language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_b22f03beeb42_key -iv $encrypted_b22f03beeb42_iv
  -in android.jks.enc -out android.jks -d
- yes | sdkmanager "platforms;android-26"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: 3xX/Y6mdxtZzOzsIGW0ytfdAXTVv0lnv81ra32/cN/q5QLHf/rehnORXllWeTJn/vORkGLSkTUAcDC0+ASu6KpyNQwtlUZaiR6OXbu/2GCsTNpaL6dxgaH2y08JZwYXnxfMqB9SHd9AQJw4zoRsDETJzyRdlCo0peVuTq78VPbI+fAOthTstbF5fFA5XkVAXqaVn9hU+9jzIySCORneicvouBjdgZKO/18ik5NhJb0wqIF4XkH9Iaav4pRxomfkDh+GlEvoxPz9dsulJn6uOgbnXdKixQImwixR/2i0rjnkXi5IVdbgH1pWg2Hp8eAf224WnOVGpALfxrd8C9vmFJIkNsU39NGczgRXovECbooPwsmJz/dPstLy7d1ZNrmqft2Y/6e27Xq/MyGBETDw7XPy3zNdcq6U0r13eNKBkZPdZp5N2GYQPbzVuAYlUfPcMXi1QZHdRdeuwXmmBjHpUN7rBQ+ZR9OgUquMFNDXitU0cUn8zgk9EgqAjkVbzsMGtwZmegwAam0rqRTVQUNriFSmdYaMZOLX6uW24Lfy8UhVLMKToxyk/rhXCTo4x/Qa14yGXPAV2Ey638tqrJLcXWghl/86nPIsOmtGskBlN4hoYLgEbDj5fRXDWi+enCD8INLrH+BVqKn5mQEl8WvpGbbnQKRbKsWcB7HIEhmvclAg=
  file: app/build/outputs/apk/release/app-release.apk
  on:
    repo: lemma-io/vivify
    tags: true
env:
  global:
    - secure: nJdt7e7DsFdgsqAYYjWKmUQtOXeKjtRZEV30jL18aoHbycwdh0juG6c108Rnu6wx5WQhPjJ0OL8/TJPI52kQwr0+TIVHTgwdJiwEqz/cIsEPAwovrr3t26D1OEIDxvS9FcTBx5sY6pkjmkLoXbGV92okw30rj+gJDS8tSIuvJUWlVDufqFM0mwsMI/LgSZqBH4NnC8F2GF1yjmxQmG8JW/Li4SZ+YlTZOK44axLTlOUgQX8Pm+e+UM2nw+6Jir/CEKSteYVBkaUZNSKJKAPQjV1mllNyF98a5PLTbB7RQqRxrRbWUkpRdkzQHmAlxKbaL/kXI9hRVkR5xfhHEfLsLws4+rbtkNUTaZxulSE+aR7hnkmOklbt0a96KZifk57Be8xbXe1pw8+LiFQr8d8fLukrNsm6enje0tBmnXW2xHLDcV92tNd6h/5DWqImQ91xen5/LLNx++9fa7wadniZjSrXbBh1Zl5wlBs86ING6byqU3aZH8k39CJuD1XzR2uXb/8esJjPNzDlWKpsHo7ltfwxBHWvtxysV9Tpqe1SBRsCEOEGOCNUBc3JiCR/8GvSPnZ1qHkSKYjDLbZgzIvQ+HAUwOyT8LxoYC4QQrXMkm1/32xXJBmuTQP8VmKXNPAjasLxhUbMe8rtXCtH6UBmL1qvMbgyhRXDYXB8Nvqb00w=
    - secure: 3+twSbMjDoVORPoDNJ6vOJpQBO+INIRu9jE+kOgMYum3ExF8HMLgbrk7esIBqp3/KYL+3gzdO6p+dsMXF6amVuwMb/gb+zC3yY8e8u5c6VjXUuE/EgjTujTwY1jjhmJwBjfrLIo8Z/hs2eldW5yE18klN8EqUS6xF4YlK/If1TVv5HR5dkTWeir7PYLOoAxxYNh4qHRbOBFMhHn22rqOJ7HvQEb0QIaS0ZBOjDny8wKP4zPtYsWXi00UOaMFP6GqBtV5Gji9TpcLFo/lhopgDYgw4V1OjZ6ngdWMf+qilY668SBOkeW5OgYCaP0M8/nyDEC8AbF+qm9WixXf+aaLBS2Ow0F1VEGL7exefGxMAvHg0DhFGMdEIpx6zwesrgpofWF2Q6po515PzLFkHNfCXgvUar1Cg80hO8NzJD/mk57wNJ+VI0ZSwnTDhVuuwqGllaAn3DPygnGx5w/c2WkIErMxVn4pZ5+xrIUAyc0LvTmyYVX7CKxs36VDUW1R0LOo3/qBx3IVBErHyHX6o5gd6XLkzXS7jbMdmTK5FrvXOOMsxqeD1CgwZB11er70dpw6enz74WKnBVj+lNs+wTg1KuLbJIUtNDcYzgwbwXSzexUiAZi+V6gFSMVnQJTqkrFBiuYprgpNPbp/7BWSo2bfE6PtKk6jjsYVCKsHk3e8oUA=
    - secure: 2UtNbaokKK59Y9GbEyFHK1ua2nOWfjnbr80nk7cb34D6xC+mmHn7ASLUxfiAV856h1w929KEmle3q5dsD7fH0g+w+yToauZrpRSYXFnHsogQzlbMYhNSZBycC49RXzidXMCgrGxRCysT2C3TmOe9F7cwQinGOVNGogMbJchLMqlrSE50I3iNScq3a4Wbf42uPFE3h+dgBS27aOTJrEKBCt1D6eNAvGSaJn6/QCvcoRdV79B7+3CJixUjyTeCbr1guTyH8YaqSxueGZHsm5RBnzPpGK4XkqaV4brDrPWr1MdoEcu9OYa3tFY63xHxORuPR5wuj8GSzhdjMXFP2Bf4eFfXjKKBP5fBfvw3Tq1zzlejC1qvNi+ikSQpcKPq9iYW235cd7e7G+9/WxHGIgf9Ih6qiBAr/KsXN6G0WBlUSXXz4aF1Q/DFnEPcuC4ehAWjw1Rm1RpuK+AwWiYGyY7/vMxMib5mT8aOj72ysDnBhJN13rlPns/1bJoBcNrggKVzULTty46gGTUO1s5AbZp6Ju1aQEU9HEAhNNCEw4bLk8Q4K7Fn1dAMXbvfkLWmssWYNlMw+l3qJl2C1pFaf5YH7J0Hr+LvQKVB81j4EGBfoE20+5EqrXGsjftgGPypHJ9Bs1VfCUvjBN5Kkx/PAgEC3r9GbxSRYGPNhidXFvqLZZc=
    - secure: bmUgjAIyeLIs0qnVKUkGo1uGAPxYCg2cWxz+bXs2xK+2FFr1Frhwo2GOP1ZibNRVY/y91NIMkZ1Zuij/YIvDqYEg4Amt+txITZusyxgzDapMV0NxefCaKH1oM26Uq7blRaLzPZ85TYSv3gj5PrnUZY3/M9+wygD2N0AVAohf3Ksnd9NBQ0y4vBhqF/XKQhc9vaKNW/e8/ZBqFucWoCQ79xXTv9ImAQBlnUt3bwjqeQVUeqwlXovzeIXAb/PtivE3V7MDmhYMtWAI7rQC+6wV4yjTdJhC16o0viy0zweEi/EkHM2sSb379ofzKWI5/5M5I+QSGYK3KlO7GJAQKveSUmKppqMv5iBnOedN35QbWlVFIHCa4G0NprJ/893cI7kDjcIbJc7nWCyfHWifQ9X7ANfTQoEwg5tJCHr8X04/KuBfiyWRtc5F5utX4NtPySe+eG44Kviy6RDEBohLbT21sWz6KncSZvnFFAKsDfNVZo045JR4Xv4GR2TfsWPZgY4weLjU5ggEqxic/inx0PiaWFwylrc2ks9GW96ST6Nr/vFHO9hZ8ZNxveeSnCH8wPCiZgHYJtbs8/io+as+o1tHxLS8k/mSAyiNKe6/HUpJgl6AJe1Gboa+B27oXGBNoEorxJf2pMbckNbyUiZ15ZY+PsIdIuPAW1OHxfJhz6NCFaI=
